#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

case "$(uname -s)" in
  Darwin*)
    brew install shellcheck
    ;;
  Linux*)
    sudo apt install shellcheck
    ;;
esac
