#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# shellcheck source=env
source "$(git rev-parse --show-toplevel)/scripts/env"

if command -v shellcheck; then
  echo "Shellcheck is already installed. Linting..."
else
  echo "Shellcheck is unavailable! Installing..."
  "${GIT_ROOT}"/scripts/lint/shellcheck/install
fi

find ./scripts -type f -exec shellcheck {} +
